---
title: "Intro to R and ODEs"
author: "sbsambado"
date: "3/21/2020"
output: html_document
---
Coursework for 1/18/2020
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Basic R commands
```{r}
## Vectors ##

#vector is a 1D array of numbers
x <- c(1,5,7)
x

# : used to generate a sequence of numbers
x<- 1:10
x

# replicate/repeat
# rep(vector, replication)
rep(1:3,2)

# repeat numbers sequentially
rep(1:3, c(2,2,2))

# y is scalar added to each element of x
x<-c(1:10)
y<-2
x+y

# multiplication of two vectors
x <-c(2,4,7)
y <-c(1,2,3)
x*y

# logical operators 
a =c(TRUE,TRUE,FALSE)
b =c(TRUE,TRUE,TRUE)
a&b

#length of vector
length(a)

# [] used to indenitfy elements of vectors
x[1] #first element of x
x[length(x)] # last element of x

# exclude elements of a vector
a <- c(5,7,9,8)
b <- a[-2]
b

# logical expresions, when expression is TRUE
x[x<5] # gives which instances are < 5 in vector x
x<5 # gives TRUE/FALSE

## Arrays and Matrices ##

# arrays and matrices are not 1D, they have dimensions

# dim() retrieve or set the dimensions of an object
x <- c(1:10)
x
dim(x) # NULL cause it's a vector

dim(x) <- c(1,10) # row,column
x

# Array

x <- array(1:20, dim = c(4,5))
x
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
